# Docker Compose for Local Development (Mac Apple Silicon / ARM64)
version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      # 本地開發使用 ARM64 (Mac M1/M2/M3)
      platforms:
        - linux/arm64
    image: creditcard-tracker-backend:local
    platform: linux/arm64
    container_name: creditcard-backend-local
    restart: unless-stopped
    ports:
      - "8444:8443"
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8443/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
